### ISSUE TITLE
Error passing the lang to the class

### ISSUE THREAD

**Issue by crgimenes** [jlsutherland/doc2text#19]
When I try to pass the language as in the example:

```
doc = doc2text.Document(lang="por")
```

I received the following error message:

```
    doc = doc2text.Document(lang="por")
TypeError: __init__() got an unexpected keyword argument 'lang'
```

**Comment by jlsutherland** [comment]
@crgimenes this should be fixed now. Thank you for flagging. We needed to push the update to PyPi.  Please update your `doc2text` dist via `pip`.
