### ISSUE TITLE
Can not install pythonmagick.

### ISSUE THREAD

**Issue by bruce3401** [jlsutherland/doc2text#27]
I tried `sudo apt-get install python-pythonmagick` and `pip install` to ensure doc2text import well. But even I successfully installed python-pythonmagick via apt, I still can not import doc2text. 

I check the source package which python-pythonmagick  installed via apt, it seems the packages can only support python2. 

So could you help to fix the problem? I want to doc2text on python3 (Ubuntu)

**Comment by jlsutherland** [comment]
Hi @dyllanwli, doc2text at present only supports python2. A python3 branch is in the works---ideally it will drop the pythonmagick dep. I'm happy to loop you back in when that branch is pushed and functional. Does that work?

**Comment by bruce3401** [comment]
Thank you, @jlsutherland.
